use eframe::egui;
use eframe::egui::{FontData, FontDefinitions, FontFamily};

pub fn setup_custom_fonts(ctx: &egui::Context) {
    let mut fonts = FontDefinitions::default();
    macro_rules! register_font {
        ($fonts:expr, $name:literal, $path:literal) => {{
            $fonts.font_data.insert(
                $name.to_owned(),
                FontData::from_static(include_bytes!($path)).into(),
            );
            $fonts
                .families
                .insert(FontFamily::Name($name.into()), vec![$name.to_owned()]);
        }};
    }

    // Inter estaticas.
    register_font!(
        fonts,
        "inter_18pt_thin",
        "../../../assets/Inter/static/Inter_18pt-Thin.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_thin_italic",
        "../../../assets/Inter/static/Inter_18pt-ThinItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_extralight",
        "../../../assets/Inter/static/Inter_18pt-ExtraLight.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_extralight_italic",
        "../../../assets/Inter/static/Inter_18pt-ExtraLightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_light",
        "../../../assets/Inter/static/Inter_18pt-Light.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_light_italic",
        "../../../assets/Inter/static/Inter_18pt-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_regular",
        "../../../assets/Inter/static/Inter_18pt-Regular.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_italic",
        "../../../assets/Inter/static/Inter_18pt-Italic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_medium",
        "../../../assets/Inter/static/Inter_18pt-Medium.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_medium_italic",
        "../../../assets/Inter/static/Inter_18pt-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_semibold",
        "../../../assets/Inter/static/Inter_18pt-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_semibold_italic",
        "../../../assets/Inter/static/Inter_18pt-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_bold",
        "../../../assets/Inter/static/Inter_18pt-Bold.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_bold_italic",
        "../../../assets/Inter/static/Inter_18pt-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_extrabold",
        "../../../assets/Inter/static/Inter_18pt-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_extrabold_italic",
        "../../../assets/Inter/static/Inter_18pt-ExtraBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_black",
        "../../../assets/Inter/static/Inter_18pt-Black.ttf"
    );
    register_font!(
        fonts,
        "inter_18pt_black_italic",
        "../../../assets/Inter/static/Inter_18pt-BlackItalic.ttf"
    );

    register_font!(
        fonts,
        "inter_24pt_thin",
        "../../../assets/Inter/static/Inter_24pt-Thin.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_thin_italic",
        "../../../assets/Inter/static/Inter_24pt-ThinItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_extralight",
        "../../../assets/Inter/static/Inter_24pt-ExtraLight.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_extralight_italic",
        "../../../assets/Inter/static/Inter_24pt-ExtraLightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_light",
        "../../../assets/Inter/static/Inter_24pt-Light.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_light_italic",
        "../../../assets/Inter/static/Inter_24pt-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_regular",
        "../../../assets/Inter/static/Inter_24pt-Regular.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_italic",
        "../../../assets/Inter/static/Inter_24pt-Italic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_medium",
        "../../../assets/Inter/static/Inter_24pt-Medium.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_medium_italic",
        "../../../assets/Inter/static/Inter_24pt-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_semibold",
        "../../../assets/Inter/static/Inter_24pt-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_semibold_italic",
        "../../../assets/Inter/static/Inter_24pt-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_bold",
        "../../../assets/Inter/static/Inter_24pt-Bold.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_bold_italic",
        "../../../assets/Inter/static/Inter_24pt-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_extrabold",
        "../../../assets/Inter/static/Inter_24pt-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_extrabold_italic",
        "../../../assets/Inter/static/Inter_24pt-ExtraBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_black",
        "../../../assets/Inter/static/Inter_24pt-Black.ttf"
    );
    register_font!(
        fonts,
        "inter_24pt_black_italic",
        "../../../assets/Inter/static/Inter_24pt-BlackItalic.ttf"
    );

    register_font!(
        fonts,
        "inter_28pt_thin",
        "../../../assets/Inter/static/Inter_28pt-Thin.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_thin_italic",
        "../../../assets/Inter/static/Inter_28pt-ThinItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_extralight",
        "../../../assets/Inter/static/Inter_28pt-ExtraLight.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_extralight_italic",
        "../../../assets/Inter/static/Inter_28pt-ExtraLightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_light",
        "../../../assets/Inter/static/Inter_28pt-Light.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_light_italic",
        "../../../assets/Inter/static/Inter_28pt-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_regular",
        "../../../assets/Inter/static/Inter_28pt-Regular.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_italic",
        "../../../assets/Inter/static/Inter_28pt-Italic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_medium",
        "../../../assets/Inter/static/Inter_28pt-Medium.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_medium_italic",
        "../../../assets/Inter/static/Inter_28pt-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_semibold",
        "../../../assets/Inter/static/Inter_28pt-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_semibold_italic",
        "../../../assets/Inter/static/Inter_28pt-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_bold",
        "../../../assets/Inter/static/Inter_28pt-Bold.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_bold_italic",
        "../../../assets/Inter/static/Inter_28pt-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_extrabold",
        "../../../assets/Inter/static/Inter_28pt-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_extrabold_italic",
        "../../../assets/Inter/static/Inter_28pt-ExtraBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_black",
        "../../../assets/Inter/static/Inter_28pt-Black.ttf"
    );
    register_font!(
        fonts,
        "inter_28pt_black_italic",
        "../../../assets/Inter/static/Inter_28pt-BlackItalic.ttf"
    );

    // Alias de compatibilidad para codigo existente.
    register_font!(
        fonts,
        "inter_regular",
        "../../../assets/Inter/static/Inter_24pt-Regular.ttf"
    );
    register_font!(
        fonts,
        "inter_italic",
        "../../../assets/Inter/static/Inter_24pt-Italic.ttf"
    );

    // Open Sans estaticas.
    register_font!(
        fonts,
        "open_sans_regular",
        "../../../assets/Open_Sans/static/OpenSans-Regular.ttf"
    );
    register_font!(
        fonts,
        "open_sans_italic",
        "../../../assets/Open_Sans/static/OpenSans-Italic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_light",
        "../../../assets/Open_Sans/static/OpenSans-Light.ttf"
    );
    register_font!(
        fonts,
        "open_sans_light_italic",
        "../../../assets/Open_Sans/static/OpenSans-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_medium",
        "../../../assets/Open_Sans/static/OpenSans-Medium.ttf"
    );
    register_font!(
        fonts,
        "open_sans_medium_italic",
        "../../../assets/Open_Sans/static/OpenSans-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semibold",
        "../../../assets/Open_Sans/static/OpenSans-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semibold_italic",
        "../../../assets/Open_Sans/static/OpenSans-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_bold",
        "../../../assets/Open_Sans/static/OpenSans-Bold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_bold_italic",
        "../../../assets/Open_Sans/static/OpenSans-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_extrabold",
        "../../../assets/Open_Sans/static/OpenSans-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_extrabold_italic",
        "../../../assets/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf"
    );

    register_font!(
        fonts,
        "open_sans_condensed_regular",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-Regular.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-Italic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_light",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-Light.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_light_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_medium",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-Medium.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_medium_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_semibold",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_semibold_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_bold",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-Bold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_bold_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_extrabold",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_condensed_extrabold_italic",
        "../../../assets/Open_Sans/static/OpenSans_Condensed-ExtraBoldItalic.ttf"
    );

    register_font!(
        fonts,
        "open_sans_semicondensed_regular",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-Regular.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-Italic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_light",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-Light.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_light_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-LightItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_medium",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-Medium.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_medium_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-MediumItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_semibold",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-SemiBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_semibold_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-SemiBoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_bold",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-Bold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_bold_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-BoldItalic.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_extrabold",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-ExtraBold.ttf"
    );
    register_font!(
        fonts,
        "open_sans_semicondensed_extrabold_italic",
        "../../../assets/Open_Sans/static/OpenSans_SemiCondensed-ExtraBoldItalic.ttf"
    );

    // Alias de compatibilidad para codigo existente.
    register_font!(
        fonts,
        "sans_regular",
        "../../../assets/Open_Sans/static/OpenSans-Regular.ttf"
    );
    register_font!(
        fonts,
        "sans_italic",
        "../../../assets/Open_Sans/static/OpenSans-Italic.ttf"
    );

    ctx.set_fonts(fonts);
}
